spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcould-config-client   
eureka:
  client:
    service-url:
      defaultZone: http://eurekadev.com:7001/eureka/
---
server:
    port: 8202   
spring:
  profiles: test
  application:
    name: springcould-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eurekatest.com:7001/eureka/