spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001   #注册中心Eureka的端口号
spring:
  profiles: dev
  application:
    name: springCould-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #自己不注册进eureka服务列表
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001   #注册中心Eureka的端口号
spring:
  profiles: test
  application:
    name: springCould-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #自己不注册进eureka服务列表
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/